name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - name: Release R20
            framework: net48
            tag: ReleaseR20Last
            path: net48
          - name: Release R21
            framework: net48
            tag: ReleaseR21Last
            path: net48
          - name: Release R22
            framework: net48
            tag: ReleaseR22Last
            path: net48
          - name: Release R23
            framework: net48
            tag: ReleaseR23Last
            path: net48
          - name: Release R24
            framework: net48
            tag: ReleaseR24Last
            path: net48
          - name: Release R25
            framework: net8.0-windows
            tag: ReleaseR25Last
            path: net8.0-windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet dependencies with version
      run: dotnet restore AnlaxTemplate.sln /p:Configuration="${{ matrix.config.name }}"

    - name: Build the solution
      run: dotnet build AnlaxTemplate.sln --configuration "${{ matrix.config.name }}"

    - name: Archive build output
      run: |
        Compress-Archive -Path "./bin/${{ matrix.config.name }}/${{ matrix.config.path }}/*" -DestinationPath "./bin/${{ matrix.config.name }}/${{ matrix.config.path }}/AnlaxBase.zip"
      shell: pwsh

    - name: Check if tag '${{ matrix.config.tag }}' exists and delete the release
      run: |
        if gh release view ${{ matrix.config.tag }}; then
          gh release delete ${{ matrix.config.tag }} -y
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.ANLAXD }}

    - name: Upload archive as release asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: '${{ matrix.config.tag }}'
        name: '${{ matrix.config.name }}'
        files: ./bin/${{ matrix.config.name }}/${{ matrix.config.path }}/AnlaxBase.zip
      env:
        GITHUB_TOKEN: ${{ secrets.ANLAXD }}